version: '3.8'

services:
  ai_api:
    container_name: summarizator_ai_api
    build:
      context: ./AI_API
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5021:5000"
    networks:
      - voice_brief_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  voice_brief_server:
    container_name: voice_brief_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/static/uploads:/usr/src/app/static/uploads
    restart: always
    env_file:
      - .env
    ports:
      - "5040:5000"
    networks:
      - voice_brief_network

networks:
  voice_brief_network:
    driver: bridge